version: '3.8'

services:
  ##########
  # CRM_DB #
  ##########
  crm_db:
    container_name: crm-db
    build:
      context: ../db
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
